/**
 * dokan script: catalog-regen  (dokan, runtime node, daily cron — cmo+cto GO 2026-06-26)
 *
 * Auto-maintains the Dokan Script Catalog (trovex doc 9356bddc) so leads stop hand-rewriting it (5×
 * in ~12h was the trigger). DESIGN (safe v1): regenerate ONLY an auto-managed LIVE-STATE block
 * delimited by HTML-comment markers; the curated prose + curated tables ABOVE the markers are NEVER
 * touched. So it's auto-accurate (live schedules/scripts straight from the API) AND preserves 100%
 * of the curated context (transport gotchas, escalation rules, per-script purpose) — a surgical
 * marker-replace, not a fragile full-doc rewrite. (v2, if cto wants it: in-place per-row regen of the
 * curated tables — riskier markdown surgery on the SSOT; deferred.)
 *
 * READ/WRITE via HTTP-MCP (proven 2026-06-26, no write-token needed):
 *   dokan  REST host.docker.internal:8088/api/{scripts,schedules} (MCP not container-reachable)
 *   trovex MCP  host.docker.internal:8765/mcp/  → trovex_read (doc full), trovex_write (doc_id)
 * Each call does a fresh init→initialized→tools/call handshake (daily script, round-trips are cheap).
 *
 * SAFETY: PREVIEW by default (writes the regenerated doc to a SCRATCH trovex doc, returns its id for
 * eyeballing); only input.commit===true writes the real catalogue 9356bddc. If the live enumeration
 * is empty/unreadable → ABORT (never write a blank section). exit 0 monitor; result on ::dokan:result::.
 * INPUT (DOKAN_INPUT, all optional): { commit, docId, dokanBase, trovexBase, scratch }.
 */
const input = (() => { try { return JSON.parse(process.env.DOKAN_INPUT || '{}'); } catch { return {}; } })();
const COMMIT = input.commit === true;
const DOC_ID = input.docId || '9356bddcb2624390b64ecaed94f8c35d';
// dokan enumeration via REST (the :8088 MCP is NOT container-reachable; REST is — memory
// dokan-8088-mcp-not-container-reachable). trovex read/write stays MCP (reachable).
const DOKAN_BASE = input.dokanBase || 'http://host.docker.internal:8088';
const TROVEX = input.trovexBase || 'http://host.docker.internal:8765/mcp/';
const BEGIN = '<!-- AUTO-CATALOG:BEGIN (regenerated by catalog-regen 443; do not hand-edit below) -->';
const END = '<!-- AUTO-CATALOG:END -->';

async function http(url, opts = {}, ms = 15000) {
  const ctl = new AbortController(); const t = setTimeout(() => ctl.abort(), ms);
  try { return await fetch(url, { ...opts, signal: ctl.signal }); } finally { clearTimeout(t); }
}
// Minimal HTTP-MCP client: handshake + one tools/call, returns the parsed tool result (content[0].text → JSON or string).
async function mcp(base, tool, args = {}) {
  let sid = null;
  const post = async (body, withSid) => {
    const h = { 'Content-Type': 'application/json', Accept: 'application/json, text/event-stream' };
    if (withSid && sid) h['Mcp-Session-Id'] = sid;
    const r = await http(base, { method: 'POST', headers: h, body: JSON.stringify(body) });
    if (!sid) sid = r.headers.get('Mcp-Session-Id');
    const txt = await r.text();
    let out = null;
    for (let line of txt.split('\n')) { line = line.trim(); if (line.startsWith('data:')) line = line.slice(5).trim(); if (!line) continue; try { const j = JSON.parse(line); if (j.result || j.error) out = j; } catch {} }
    return out;
  };
  await post({ jsonrpc: '2.0', id: 1, method: 'initialize', params: { protocolVersion: '2025-06-18', capabilities: {}, clientInfo: { name: 'catalog-regen', version: '1' } } }, false);
  await post({ jsonrpc: '2.0', method: 'notifications/initialized' }, true);
  const res = await post({ jsonrpc: '2.0', id: 1, method: 'tools/call', params: { name: tool, arguments: args } }, true);
  const text = res?.result?.content?.[0]?.text;
  if (text == null) return null;
  try { return JSON.parse(text); } catch { return text; }
}

(async () => {
  const dokanGet = async (path) => {
    try {
      const r = await http(`${DOKAN_BASE}${path}`, { headers: process.env.DOKAN_TOKEN ? { Authorization: `Bearer ${process.env.DOKAN_TOKEN}` } : {} });
      if (!r.ok) return null;
      return await r.json();
    } catch { return null; }
  };
  const scriptsRes = await dokanGet('/api/scripts');
  const schedRes = await dokanGet('/api/schedules');
  const scripts = (scriptsRes && (scriptsRes.scripts || scriptsRes)) || null;
  const schedules = (schedRes && (schedRes.schedules || schedRes)) || null;
  if (!Array.isArray(scripts) || !Array.isArray(schedules) || scripts.length === 0) {
    console.log(`::dokan:result:: ${JSON.stringify({ error: 'enumeration_unreadable', scripts: Array.isArray(scripts) ? scripts.length : null, schedules: Array.isArray(schedules) ? schedules.length : null })}`);
    console.log('catalog-regen: could not enumerate live scripts/schedules — aborting (no write)');
    return; // never write a blank section
  }

  const byId = new Map(scripts.map((s) => [s.id, s]));
  const esc = (v) => String(v == null ? '' : v).replace(/\|/g, '\\|');
  const schedRows = [...schedules].sort((a, b) => a.schedule_id - b.schedule_id)
    .map((s) => `| ${s.schedule_id} | ${s.script_id} | ${esc(s.script_name || s.script || byId.get(s.script_id)?.name)} | \`${esc(s.cron)}\` | ${esc(byId.get(s.script_id)?.created_by) || '?'} |`);
  const scriptRows = [...scripts].sort((a, b) => a.id - b.id)
    .map((s) => `| ${s.id} | ${esc(s.name)} | ${esc(s.runtime)} | ${esc(s.created_by) || '?'} |`);

  const block = [
    BEGIN,
    '## Live state (auto-generated — ground truth)',
    '',
    `_Regenerated daily by \`catalog-regen\` (dokan 443) from \`list_scripts\` + \`list_schedules\`. Always current. The curated catalogue above is hand-owned; if a curated row disagrees with this, this wins on the bare facts (id/cron/owner)._`,
    '',
    `### Live schedules (${schedules.length})`,
    '| schedule | script_id | script | cron | created_by |',
    '|---|---|---|---|---|',
    ...schedRows,
    '',
    `### Live scripts (${scripts.length})`,
    '| id | name | runtime | created_by |',
    '|---|---|---|---|',
    ...scriptRows,
    '',
    END,
  ].join('\n');

  const doc = await mcp(TROVEX, 'trovex_read', { doc_id: DOC_ID, full: true });
  const cur = typeof doc === 'string' ? doc : (doc?.result || doc?.text || '');
  if (!cur || cur.length < 200) {
    console.log(`::dokan:result:: ${JSON.stringify({ error: 'doc_read_failed', docId: DOC_ID, got: typeof doc })}`);
    console.log('catalog-regen: could not read the catalogue doc — aborting (no write)');
    return;
  }

  let next;
  const bi = cur.indexOf(BEGIN);
  if (bi !== -1) {
    const ei = cur.indexOf(END, bi);
    next = cur.slice(0, bi).replace(/\s*$/, '\n\n') + block + cur.slice(ei === -1 ? cur.length : ei + END.length);
  } else {
    next = cur.replace(/\s*$/, '\n\n') + block + '\n';
  }

  if (!COMMIT) {
    const scratch = await mcp(TROVEX, 'trovex_write', { content: `# Catalog-regen PREVIEW (scratch)\n\nPreview of the auto LIVE-STATE block + merged doc. Safe to delete. Set commit:true to write ${DOC_ID}.\n\n---\n\n${next}`, force: true, tags: ['type/scratch', 'owner/fullstack-lead'] });
    const sid = typeof scratch === 'string' ? scratch : (scratch?.result || '?');
    console.log(`::dokan:result:: ${JSON.stringify({ mode: 'preview', scratch_doc: sid, schedules: schedules.length, scripts: scripts.length, marker_existed: bi !== -1 })}`);
    console.log(`catalog-regen: PREVIEW written to scratch ${sid} (${schedules.length} sched, ${scripts.length} scripts). commit:true to write the real doc.`);
    return;
  }

  const w = await mcp(TROVEX, 'trovex_write', { doc_id: DOC_ID, content: next });
  const wid = typeof w === 'string' ? w : (w?.result || '?');
  console.log(`::dokan:result:: ${JSON.stringify({ mode: 'commit', doc: wid, schedules: schedules.length, scripts: scripts.length, marker_existed: bi !== -1 })}`);
  console.log(`catalog-regen: COMMITTED ${wid} (${schedules.length} sched, ${scripts.length} scripts).`);
})();
